version: "3"
services:
  redis:
    image: redis/redis-stack
    ports:
      - 6379:6379
      - "8001:8001"
    networks:
      - job-apply-bot-net
  job-apply-bot-db:
    image: postgres
    container_name: job-apply-bot-db
    restart: always
    environment:
      POSTGRES_DB: job-apply-bot
      # POSTGRES_USER: motobyo
      POSTGRES_PASSWORD: test1234!
    ports:
      - 5432:5432
    networks:
      - job-apply-bot-net

networks:
  job-apply-bot-net:
